name: Terraform CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tf-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Formatting check (no backend needed)
      - name: terraform fmt (check)
        run: terraform fmt -check -diff

      # Validate syntax/providers without touching your remote state
      - name: terraform init (no backend)
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: TFLint init
        run: tflint --init

      - name: TFLint run
        run: tflint

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov

      - name: Checkov (Terraform scan)
        working-directory: terraform
        run: |
          # Option 1: never fail the build
          # checkov -d . --framework terraform --soft-fail --config-file ../terraform/.checkov.yml

          # Option 2: only fail on HIGH (uncomment this, remove the line above)
          checkov -d . --framework terraform --hard-fail-on HIGH --soft-fail-on MEDIUM,LOW --config-file ../terraform/.checkov.yml

